//! Ambiguous question generation.
//!
//! Generates `@q[ambiguous]` questions for unclear phrasing
//! that needs clarification.

use std::collections::HashSet;

use chrono::Utc;

use crate::models::{QuestionType, ReviewQuestion};
use crate::patterns::{extract_frontmatter_reviewed_date, extract_reviewed_date};

use super::iter_fact_lines;

/// Default number of days a reviewed marker suppresses question regeneration.
const REVIEWED_SKIP_DAYS: i64 = 180;

/// Default document types treated as glossary/definitions.
const DEFAULT_GLOSSARY_TYPES: &[&str] = &["definition", "definitions", "glossary", "reference"];

/// Check if a document is a glossary/definition/reference document.
///
/// Matches by doc_type against `glossary_types` (or defaults) or by
/// title in the first 3 lines (`# Glossary`, `# Definitions`).
pub fn is_glossary_doc(doc_type: Option<&str>, content: &str) -> bool {
    is_glossary_doc_with_types(doc_type, content, None)
}

/// Check if a document is a glossary/definition/reference document,
/// with optional custom glossary types from perspective.yaml.
pub fn is_glossary_doc_with_types(
    doc_type: Option<&str>,
    content: &str,
    custom_types: Option<&[String]>,
) -> bool {
    doc_type.is_some_and(|t| {
        let l = t.to_lowercase();
        if let Some(types) = custom_types {
            types.iter().any(|ct| ct.to_lowercase() == l)
                || DEFAULT_GLOSSARY_TYPES.iter().any(|d| *d == l)
        } else {
            DEFAULT_GLOSSARY_TYPES.iter().any(|d| *d == l)
        }
    }) || {
        let fm_lines = crate::patterns::frontmatter_line_count(content);
        content.lines().skip(fm_lines).take(3).any(|l| {
            let lower = l.to_lowercase();
            lower.contains("# glossary") || lower.contains("# definitions")
        })
    }
}

/// Extract defined terms from a definitions/glossary document.
///
/// Parses `**TERM**:` patterns (the standard definitions file format) and
/// `## TERM` headings, returning the set of defined terms.
pub fn extract_defined_terms(content: &str) -> HashSet<String> {
    let mut terms = HashSet::new();
    for line in content.lines() {
        let trimmed = line.trim().trim_start_matches("- ");
        // Match **TERM**: definition pattern
        if let Some(rest) = trimmed.strip_prefix("**") {
            if let Some(end) = rest.find("**") {
                let term = rest[..end].trim();
                if !term.is_empty() {
                    terms.insert(term.to_string());
                }
            }
        }
        // Match ## TERM heading pattern
        if let Some(heading) = trimmed.strip_prefix("## ") {
            let term = heading.trim();
            if !term.is_empty() && !term.contains(' ') {
                terms.insert(term.to_string());
            }
        }
    }
    terms
}

/// Extract the acronym from an ambiguous question description.
///
/// Matches the pattern `what does "XXX" mean in this context?` generated by
/// `detect_undefined_acronym`. Returns `None` for non-acronym ambiguous questions.
pub fn extract_acronym_from_question(description: &str) -> Option<String> {
    let marker = "what does \"";
    let start = description.find(marker)? + marker.len();
    let end = description[start..].find('"')? + start;
    Some(description[start..end].to_string())
}

/// Collect all defined terms from glossary/definition/reference documents.
pub fn collect_defined_terms(docs: &[crate::models::Document]) -> HashSet<String> {
    collect_defined_terms_with_types(docs, None)
}

/// Collect all defined terms from glossary/definition/reference documents,
/// with optional custom glossary types from perspective.yaml.
///
/// Includes:
/// - Terms extracted from glossary doc content (`**TERM**:`, `## TERM`)
/// - Titles of ALL documents — any entity with its own document is implicitly
///   defined in the KB (entity name matching). This suppresses ambiguous questions
///   for acronyms like "SME" when a document titled "SME" already exists.
pub fn collect_defined_terms_with_types(
    docs: &[crate::models::Document],
    glossary_types: Option<&[String]>,
) -> HashSet<String> {
    let mut terms = HashSet::new();
    for doc in docs {
        // All document titles are implicitly defined — any entity with its own
        // document is defined in the KB (entity name matching).
        if !doc.title.is_empty() {
            terms.insert(doc.title.clone());
        }
        // For glossary/definition docs, also extract inline term definitions
        // (e.g. **TERM**: definition, ## TERM headings).
        if is_glossary_doc_with_types(doc.doc_type.as_deref(), &doc.content, glossary_types) {
            terms.extend(extract_defined_terms(&doc.content));
        }
    }
    terms
}

/// Generate ambiguous questions for a document.
///
/// Detects facts with unclear phrasing that needs clarification:
/// 1. Locations without context (could be home, work, or other)
/// 2. Relationships without direction (e.g., "knows John" - professional or personal?)
/// 3. Vague pronouns or references
///
/// Returns a list of `ReviewQuestion` with `question_type = Ambiguous`.
pub fn generate_ambiguous_questions(content: &str) -> Vec<ReviewQuestion> {
    generate_ambiguous_questions_with_type(content, None, &HashSet::new())
}

/// Generate ambiguous questions, optionally skipping acronym detection for definition documents.
///
/// `defined_terms` contains terms from definitions files in the repo that should
/// not be flagged as undefined acronyms.
pub fn generate_ambiguous_questions_with_type(
    content: &str,
    doc_type: Option<&str>,
    defined_terms: &HashSet<String>,
) -> Vec<ReviewQuestion> {
    let mut questions = Vec::new();
    let today = Utc::now().date_naive();

    // Check frontmatter for document-level reviewed date (obsidian format)
    let fm_skip = extract_frontmatter_reviewed_date(content)
        .is_some_and(|d| (today - d).num_days() <= REVIEWED_SKIP_DAYS);

    // Skip acronym detection for glossary/definition documents
    let skip_acronyms = is_glossary_doc(doc_type, content);

    for (line_number, line, fact_text) in iter_fact_lines(content) {
        // Skip facts with a recent reviewed marker (inline or frontmatter)
        if fm_skip
            || extract_reviewed_date(line)
                .is_some_and(|d| (today - d).num_days() <= REVIEWED_SKIP_DAYS)
        {
            continue;
        }

        // Check for ambiguous location (no context like "home", "work", "office")
        let ambiguity = detect_ambiguous_location(&fact_text)
            .or_else(|| detect_ambiguous_relationship(&fact_text))
            .map(String::from)
            .or_else(|| {
                if skip_acronyms {
                    None
                } else {
                    detect_undefined_acronym(&fact_text, defined_terms)
                }
            });

        if let Some(ambiguity) = ambiguity {
            questions.push(ReviewQuestion::new(
                QuestionType::Ambiguous,
                Some(line_number),
                format!("\"{fact_text}\" - {ambiguity}"),
            ));
        }
    }

    questions
}

/// Detect ambiguous location references.
/// Returns Some(clarification_question) if ambiguous, None otherwise.
fn detect_ambiguous_location(text: &str) -> Option<&'static str> {
    let lower = text.to_lowercase();

    // Location phrases that need context
    let location_phrases = ["lives in", "based in", "located in", "resides in"];

    // Context words that clarify the location type
    let context_words = [
        "home",
        "work",
        "office",
        "headquarters",
        "hq",
        "remote",
        "primary",
        "secondary",
        "main",
    ];

    // Check if it's a location statement
    let is_location = location_phrases.iter().any(|p| lower.contains(p));
    if !is_location {
        return None;
    }

    // Check if context is provided
    let has_context = context_words.iter().any(|c| lower.contains(c));
    if has_context {
        return None;
    }

    Some("is this home, work, or another type of location?")
}

/// Detect ambiguous relationship references.
/// Returns Some(clarification_question) if ambiguous, None otherwise.
fn detect_ambiguous_relationship(text: &str) -> Option<&'static str> {
    let lower = text.to_lowercase();

    // Vague relationship phrases
    let vague_relationships = [
        ("knows ", "is this a professional or personal relationship?"),
        ("connected to ", "what is the nature of this connection?"),
        (
            "associated with ",
            "what is the nature of this association?",
        ),
        (
            "works with ",
            "is this a direct colleague, collaborator, or other?",
        ),
        ("met ", "in what context did they meet?"),
    ];

    for (phrase, question) in vague_relationships {
        if lower.contains(phrase) {
            // Check if there's already clarifying context
            let clarifiers = [
                "colleague",
                "friend",
                "mentor",
                "manager",
                "report",
                "client",
                "partner",
                "investor",
                "advisor",
                "board",
                "professional",
                "personal",
            ];
            let has_clarifier = clarifiers.iter().any(|c| lower.contains(c));
            if !has_clarifier {
                return Some(question);
            }
        }
    }

    None
}

/// Check if a word is a valid Roman numeral (I through MMMCMXCIX / 1-3999).
///
/// Standard ordinal suffixes like II, III, IV, VIII, XIV etc. appear in proper
/// nouns across many domains (monarchs, popes, ship classes, sequels) and should
/// not be flagged as undefined acronyms.
fn is_roman_numeral(s: &str) -> bool {
    use std::sync::LazyLock;
    static RE: LazyLock<regex::Regex> = LazyLock::new(|| {
        regex::Regex::new(r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$")
            .expect("roman numeral regex should compile")
    });
    !s.is_empty() && RE.is_match(s)
}

/// Detect undefined acronyms/abbreviations that could have multiple meanings.
///
/// Flags uppercase sequences (2-5 chars) that aren't preceded by their expansion
/// in the same line or a nearby heading. Common well-known acronyms are excluded.
fn detect_undefined_acronym(text: &str, defined_terms: &HashSet<String>) -> Option<String> {
    // Well-known acronyms that don't need definition in a knowledge base context.
    // Includes business, tech, cloud/AWS, and general industry terms.
    static KNOWN: &[&str] = &[
        // Business & titles
        "CEO", "CTO", "CFO", "COO", "CMO", "CIO", "CISO", "CPO", "CRO", "CSO", "VP", "SVP", "EVP",
        "MD", "PhD", "MBA", "BS", "BA", "MS", "JD", "HR", "IT", "PM", "AM", "IPO", "LLC", "INC",
        "LTD", "PLC", "AG", "Q1", "Q2", "Q3", "Q4", "YoY", "QoQ", "MoM", "KPI", "OKR", "ROI",
        "P&L", "R&D", "M&A", "SaaS", "PaaS", "IaaS", "B2B", "B2C", "B2G", "D2C", "PR", "IR", "VC",
        "PE", "LP", "GP", "ARR", "MRR", "GMV", "TAM", "SAM", "SOM", "NPS", "CAC", "LTV", "EBITDA",
        "FTE", "PTO", "WFH", "RTO", "OOO", // Geography & general
        "US", "USA", "UK", "EU", "UN", "NATO", "USD", "EUR", "GBP", "JPY", "CAD", "AUD", "NYC",
        "SF", "LA", "DC", "HQ", "NA", "EMEA", "APAC", "LATAM", "AMER", "ANZ", "DACH", "ASAP",
        "TBD", "TBA", "ID", "OK", "ETA", "EOD", "COB", // Core tech
        "AI", "ML", "LLM", "NLP", "GPU", "CPU", "RAM", "SSD", "HDD", "API", "SDK", "CLI", "GUI",
        "IDE", "URL", "URI", "SQL", "DB", "ORM", "ETL", "ELT", "DNS", "HTTP", "HTTPS", "SSH",
        "TCP", "IP", "UDP", "TLS", "SSL", "REST", "RPC", "gRPC", "MQTT", "AMQP", "PDF", "CSV",
        "JSON", "YAML", "XML", "HTML", "CSS", "JS", "TS", "CI", "CD", "QA", "UAT", "SLA", "SLO",
        "SLI", "OS", "VM", "VPN", "SSO", "MFA", "RBAC", "IAM", "LDAP", "SAML", "CRUD", "CQRS",
        "DDD", "TDD", "BDD", "OOP", "JWT", "OAuth", "OIDC", "CIDR", "VLAN", "BGP", "CDN", "WAF",
        // AWS services & terms
        "AWS", "EC2", "S3", "RDS", "ECS", "EKS", "ELB", "ALB", "NLB", "VPC", "SNS", "SQS", "SES",
        "DMS", "KMS", "ACM", "EMR", "MSK", "MQ", "DAX", "DDB", "EBS", "EFS", "FSx", "ECR", "EKS",
        "ECS", "WAF", "ACL", "NAT", "IGW", "SSM", "ASG", "AMI", "AZ", "ARN",
        // Other cloud & infra
        "GCP", "GKE", "GCE", "GCS", "K8s", "CNCF", "OCI", "WASM", "SOC", "PCI", "DSS", "HIPAA",
        "GDPR", "SOX", "FedRAMP",
    ];

    // Find uppercase sequences of 2-5 chars that look like acronyms
    let mut found: Option<&str> = None;
    for word in text.split(|c: char| !c.is_alphanumeric() && c != '&') {
        let trimmed = word.trim();
        if trimmed.len() < 2 || trimmed.len() > 5 {
            continue;
        }
        // Must be mostly uppercase letters (allow digits like "S3" or "&" like "P&L")
        let alpha_chars: Vec<char> = trimmed.chars().filter(|c| c.is_alphabetic()).collect();
        if alpha_chars.len() < 2 || !alpha_chars.iter().all(|c| c.is_uppercase()) {
            continue;
        }
        if KNOWN.iter().any(|k| k.eq_ignore_ascii_case(trimmed)) {
            continue;
        }
        // Skip valid Roman numerals (ordinal suffixes in proper nouns)
        if is_roman_numeral(trimmed) {
            continue;
        }
        // Skip terms defined in the repo's definitions files
        if defined_terms
            .iter()
            .any(|t| t.eq_ignore_ascii_case(trimmed))
        {
            continue;
        }
        // Check if the expansion appears in the same line (e.g., "Total Addressable Market (TAM)")
        let lower = text.to_lowercase();
        let acronym_lower = trimmed.to_lowercase();
        if lower.contains(&format!("({acronym_lower})")) || lower.contains(&format!("({trimmed})"))
        {
            continue;
        }
        found = Some(trimmed);
        break; // One per fact line
    }

    found.map(|acronym| format!("what does \"{acronym}\" mean in this context? Consider creating a definitions/ doc for this term"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_ambiguous_questions_no_facts() {
        assert!(generate_ambiguous_questions("# Title\n\nSome paragraph text.").is_empty());
    }

    #[test]
    fn test_generate_ambiguous_questions_location() {
        // Without context → flagged
        let q = generate_ambiguous_questions("# Person\n\n- Lives in San Francisco");
        assert_eq!(q.len(), 1);
        assert_eq!(q[0].question_type, QuestionType::Ambiguous);
        assert!(q[0].description.contains("home, work, or another"));
        // With context → not flagged
        assert!(
            generate_ambiguous_questions("# Person\n\n- Lives in San Francisco (home)").is_empty()
        );
        assert!(generate_ambiguous_questions("# Person\n\n- Based in NYC office").is_empty());
    }

    #[test]
    fn test_generate_ambiguous_questions_relationship() {
        // Vague → flagged
        let q = generate_ambiguous_questions("# Person\n\n- Knows John Smith");
        assert_eq!(q.len(), 1);
        assert!(q[0].description.contains("professional or personal"));
        // With context → not flagged
        assert!(generate_ambiguous_questions(
            "# Person\n\n- Knows John Smith (colleague from Acme)"
        )
        .is_empty());
    }

    #[test]
    fn test_generate_ambiguous_questions_works_with() {
        let q = generate_ambiguous_questions("# Person\n\n- Works with Jane Doe");
        assert_eq!(q.len(), 1);
        assert!(q[0].description.contains("direct colleague, collaborator"));
        assert!(
            generate_ambiguous_questions("# Person\n\n- Works with Jane Doe as her manager")
                .is_empty()
        );
    }

    #[test]
    fn test_generate_ambiguous_questions_met() {
        let q = generate_ambiguous_questions("# Person\n\n- Met Bob at a conference");
        assert_eq!(q.len(), 1);
        assert!(q[0].description.contains("context"));
    }

    #[test]
    fn test_generate_ambiguous_questions_line_numbers_and_multiple() {
        let content = "# Person\n\n- Clear fact\n- Lives in Boston\n- Another clear fact";
        let q = generate_ambiguous_questions(content);
        assert_eq!(q[0].line_ref, Some(4));

        let q2 = generate_ambiguous_questions("# Person\n\n- Lives in NYC\n- Knows Jane");
        assert_eq!(q2.len(), 2);
    }

    #[test]
    fn test_detect_ambiguous_location() {
        for phrase in [
            "Lives in NYC",
            "Based in London",
            "Located in Paris",
            "Resides in Tokyo",
        ] {
            assert!(
                detect_ambiguous_location(phrase).is_some(),
                "Should flag: {}",
                phrase
            );
        }
        for phrase in [
            "Lives in NYC (home)",
            "Based in London office",
            "Located in Paris headquarters",
            "Primary residence in Tokyo",
        ] {
            assert!(
                detect_ambiguous_location(phrase).is_none(),
                "Should NOT flag: {}",
                phrase
            );
        }
    }

    #[test]
    fn test_detect_ambiguous_relationship() {
        for phrase in [
            "Knows John",
            "Connected to Jane",
            "Associated with Acme",
            "Works with Bob",
        ] {
            assert!(
                detect_ambiguous_relationship(phrase).is_some(),
                "Should flag: {}",
                phrase
            );
        }
        for phrase in [
            "Knows John (colleague)",
            "Connected to Jane as mentor",
            "Works with Bob as his manager",
            "Met Jane, now a close friend",
        ] {
            assert!(
                detect_ambiguous_relationship(phrase).is_none(),
                "Should NOT flag: {}",
                phrase
            );
        }
    }

    #[test]
    fn test_reviewed_marker_suppresses_ambiguous() {
        let today = Utc::now().date_naive();
        let marker_date = today - chrono::Duration::days(30);
        let content = format!(
            "# Person\n\n- Lives in San Francisco <!-- reviewed:{} -->",
            marker_date.format("%Y-%m-%d")
        );
        assert!(generate_ambiguous_questions(&content).is_empty());
        // Old marker does NOT suppress
        assert_eq!(
            generate_ambiguous_questions(
                "# Person\n\n- Lives in San Francisco <!-- reviewed:2020-01-01 -->"
            )
            .len(),
            1
        );
    }

    #[test]
    fn test_acronym_detection() {
        // Unknown acronym flagged
        let q = generate_ambiguous_questions("# Company\n\n- Leading XYZQ expansion in healthcare");
        assert_eq!(q.len(), 1);
        assert!(q[0].description.contains("XYZQ"));

        // Known acronyms not flagged
        for acronym in ["CTO", "ECS", "RDS", "SOC", "TAM", "VPC", "SQS", "AWS"] {
            let content = format!("# Project\n\n- Uses {acronym} for deployment");
            let qs = generate_ambiguous_questions(&content);
            assert!(
                qs.iter().all(|q| !q.description.contains(acronym)),
                "{acronym} should not be flagged"
            );
        }

        // Expanded acronym not flagged
        let q2 =
            generate_ambiguous_questions("# Company\n\n- Total Addressable Market (TAM) is $5B");
        assert!(q2.iter().all(|q| !q.description.contains("TAM")));

        // Short uppercase word not flagged
        let q3 = generate_ambiguous_questions("# Doc\n\n- Phase A of the project");
        assert!(q3.iter().all(|q| !q.description.contains("what does")));

        // Only first unknown acronym per line flagged
        let q4 = generate_ambiguous_questions("# Doc\n\n- Working on XYZQ and ABCD analysis");
        assert_eq!(
            q4.iter()
                .filter(|q| q.description.contains("what does"))
                .count(),
            1
        );
    }

    #[test]
    fn test_extract_defined_terms() {
        // Bold pattern
        let c1 = "# Definitions\n\n## Acronyms\n- **TAM**: Total Addressable Market\n- **NPS**: Net Promoter Score\n";
        let t1 = extract_defined_terms(c1);
        assert!(t1.contains("TAM") && t1.contains("NPS"));
        // Heading pattern
        let c2 = "# Glossary\n\n## XYZQ\nSome custom term\n\n## ABCD\nAnother term\n";
        let t2 = extract_defined_terms(c2);
        assert!(t2.contains("XYZQ") && t2.contains("ABCD"));
        // Multi-word headings ignored
        assert!(extract_defined_terms("# Glossary\n\n## Some Phrase\nNot a term\n").is_empty());
    }

    #[test]
    fn test_defined_terms_suppress_acronym_questions() {
        let defined = HashSet::from(["XYZQ".to_string()]);
        // Defined term not flagged
        let q1 = generate_ambiguous_questions_with_type(
            "# Company\n\n- Uses XYZQ for analytics",
            None,
            &defined,
        );
        assert!(q1.iter().all(|q| !q.description.contains("XYZQ")));
        // Case-insensitive
        let defined2 = HashSet::from(["xyzq".to_string()]);
        let q2 = generate_ambiguous_questions_with_type(
            "# Company\n\n- Uses XYZQ for analytics",
            None,
            &defined2,
        );
        assert!(q2.iter().all(|q| !q.description.contains("XYZQ")));
        // Undefined term still flagged
        let q3 = generate_ambiguous_questions_with_type(
            "# Company\n\n- Uses ABCD for analytics",
            None,
            &defined,
        );
        assert_eq!(
            q3.iter().filter(|q| q.description.contains("ABCD")).count(),
            1
        );
    }

    #[test]
    fn test_is_roman_numeral() {
        // Valid Roman numerals
        for s in [
            "II", "III", "IV", "VI", "VII", "VIII", "IX", "XI", "XII", "XIV", "XV", "XX", "XXI",
            "XL", "CD", "CM", "MM", "MCMX",
        ] {
            assert!(is_roman_numeral(s), "{s} should be a Roman numeral");
        }
        // Not Roman numerals
        for s in ["", "A", "AB", "CEO", "AWS", "XYZQ", "IC", "VIP", "DM"] {
            assert!(!is_roman_numeral(s), "{s} should NOT be a Roman numeral");
        }
    }

    #[test]
    fn test_roman_numerals_not_flagged_as_acronyms() {
        // Roman numeral ordinals in proper nouns should not generate questions
        for name in [
            "Sargon II",
            "Tiglath-Pileser III",
            "Nebuchadnezzar II",
            "Henry VIII",
            "Louis XIV",
            "Elizabeth II",
            "Pope Pius XII",
        ] {
            let content = format!("# Entity\n\n- {name} ruled the empire");
            let q = generate_ambiguous_questions(&content);
            assert!(
                q.iter().all(|q| !q.description.contains("what does")),
                "Roman numeral in '{name}' should not be flagged"
            );
        }
        // Non-Roman-numeral acronyms still flagged
        let q = generate_ambiguous_questions("# Entity\n\n- Joined XYZQ in 2020");
        assert!(q.iter().any(|q| q.description.contains("XYZQ")));
    }

    #[test]
    fn test_is_glossary_doc() {
        // By doc_type
        assert!(is_glossary_doc(Some("glossary"), "# Something"));
        assert!(is_glossary_doc(Some("definition"), "# Something"));
        assert!(is_glossary_doc(Some("reference"), "# Something"));
        assert!(is_glossary_doc(Some("Glossary"), "# Something"));
        assert!(is_glossary_doc(Some("Reference"), "# Something"));
        // By title in content
        assert!(is_glossary_doc(
            None,
            "---\nfactbase_id: abc123\n---\n# Glossary\n\n- **TERM**: def"
        ));
        assert!(is_glossary_doc(None, "# Definitions\n\n- **TERM**: def"));
        // Not a glossary
        assert!(!is_glossary_doc(Some("person"), "# John Smith"));
        assert!(!is_glossary_doc(None, "# Project Overview"));
    }

    #[test]
    fn test_collect_defined_terms() {
        use crate::models::Document;
        let glossary = Document {
            id: "aaa".to_string(),
            title: "Glossary".to_string(),
            content: "# Glossary\n\n- **HCLS**: Healthcare and Life Sciences\n- **RFP**: Request for Proposal\n".to_string(),
            doc_type: Some("glossary".to_string()),
            ..Document::test_default()
        };
        let regular = Document {
            id: "bbb".to_string(),
            title: "Project".to_string(),
            content: "# Project\n\n- Uses HCLS framework\n".to_string(),
            doc_type: Some("project".to_string()),
            ..Document::test_default()
        };
        let terms = collect_defined_terms(&[glossary, regular]);
        assert!(terms.contains("HCLS"));
        assert!(terms.contains("RFP"));
        assert!(terms.contains("Glossary")); // glossary doc title
        assert!(terms.contains("Project")); // all doc titles are now included
    }

    #[test]
    fn test_glossary_terms_suppress_ambiguous_in_other_docs() {
        use crate::models::Document;
        let glossary = Document {
            id: "ggg".to_string(),
            title: "Glossary".to_string(),
            content: "# Glossary\n\n- **HCLS**: Healthcare and Life Sciences\n- **RFP**: Request for Proposal\n".to_string(),
            doc_type: Some("glossary".to_string()),
            ..Document::test_default()
        };
        let terms = collect_defined_terms(&[glossary]);
        // HCLS defined in glossary → not flagged
        let q = generate_ambiguous_questions_with_type(
            "# Project\n\n- Expanding HCLS practice",
            None,
            &terms,
        );
        assert!(q.iter().all(|q| !q.description.contains("HCLS")));
        // Unknown acronym still flagged
        let q2 = generate_ambiguous_questions_with_type(
            "# Project\n\n- Working on XYZQ initiative",
            None,
            &terms,
        );
        assert!(q2.iter().any(|q| q.description.contains("XYZQ")));
    }

    #[test]
    fn test_reference_type_skips_acronym_detection() {
        // Documents with type "reference" should skip acronym detection entirely
        let q = generate_ambiguous_questions_with_type(
            "# AWS Lambda\n\n- Uses XYZQ for processing",
            Some("reference"),
            &HashSet::new(),
        );
        assert!(q.iter().all(|q| !q.description.contains("XYZQ")));
    }

    #[test]
    fn test_extract_acronym_from_question() {
        assert_eq!(
            extract_acronym_from_question(
                "\"Uses SA for deployment\" - what does \"SA\" mean in this context?"
            ),
            Some("SA".to_string())
        );
        assert_eq!(
            extract_acronym_from_question(
                "\"HCLS practice\" - what does \"HCLS\" mean in this context?"
            ),
            Some("HCLS".to_string())
        );
        // Non-acronym ambiguous questions return None
        assert_eq!(
            extract_acronym_from_question(
                "\"Lives in NYC\" - is this home, work, or another type of location?"
            ),
            None
        );
        assert_eq!(extract_acronym_from_question(""), None);
    }

    #[test]
    fn test_definitions_plural_type_recognized_as_glossary() {
        // Documents with type "definitions" (plural, from folder name) should be glossary docs
        assert!(is_glossary_doc(
            Some("definitions"),
            "# SA\n\n- Solutions Architect"
        ));
        assert!(is_glossary_doc(
            Some("Definitions"),
            "# SA\n\n- Solutions Architect"
        ));
    }

    #[test]
    fn test_doc_titles_included_as_defined_terms() {
        use crate::models::Document;
        // Individual definition docs (one-doc-per-term layout like definitions/SA.md)
        let sa_doc = Document {
            id: "aaa".to_string(),
            title: "SA".to_string(),
            content: "# SA\n\n- **SA**: Solutions Architect\n".to_string(),
            doc_type: Some("definitions".to_string()),
            ..Document::test_default()
        };
        let hcls_doc = Document {
            id: "bbb".to_string(),
            title: "HCLS".to_string(),
            content: "# HCLS\n\nHealthcare and Life Sciences\n".to_string(),
            doc_type: Some("definitions".to_string()),
            ..Document::test_default()
        };
        let terms = collect_defined_terms(&[sa_doc, hcls_doc]);
        // Both titles and content terms should be included
        assert!(
            terms.contains("SA"),
            "doc title SA should be a defined term"
        );
        assert!(
            terms.contains("HCLS"),
            "doc title HCLS should be a defined term"
        );
    }

    #[test]
    fn test_definitions_docs_suppress_ambiguous_questions() {
        use crate::models::Document;
        // Simulate definitions/ folder with individual docs
        let sa_doc = Document {
            id: "d01".to_string(),
            title: "SA".to_string(),
            content: "# SA\n\n- Solutions Architect\n".to_string(),
            doc_type: Some("definitions".to_string()),
            ..Document::test_default()
        };
        let terms = collect_defined_terms(&[sa_doc]);
        // SA should not be flagged as ambiguous in other docs
        let q = generate_ambiguous_questions_with_type(
            "# Project\n\n- Working with SA team on deployment",
            Some("project"),
            &terms,
        );
        assert!(
            q.iter().all(|q| !q.description.contains("SA")),
            "SA should be suppressed by definitions doc"
        );
    }

    #[test]
    fn test_unknown_acronym_suggests_definitions_doc() {
        // Unknown acronyms should include a suggestion to create a definitions doc
        let q = generate_ambiguous_questions("# Project\n\n- Uses XYZQ for analytics");
        assert_eq!(q.len(), 1);
        assert!(
            q[0].description
                .contains("Consider creating a definitions/ doc"),
            "Should suggest creating a definitions doc, got: {}",
            q[0].description
        );
    }

    #[test]
    fn test_all_doc_titles_suppress_ambiguous_questions() {
        use crate::models::Document;
        // A non-glossary doc titled "SME" — its title alone should suppress the question
        let sme_doc = Document {
            id: "sme1".to_string(),
            title: "SME".to_string(),
            content: "# SME\n\n- Subject Matter Expert\n".to_string(),
            doc_type: Some("concepts".to_string()), // NOT a glossary type
            ..Document::test_default()
        };
        let terms = collect_defined_terms(&[sme_doc]);
        assert!(terms.contains("SME"), "doc title SME should be a defined term");
        // SME should not be flagged as ambiguous in other docs
        let q = generate_ambiguous_questions_with_type(
            "# Project\n\n- Working with SME team on deployment",
            Some("project"),
            &terms,
        );
        assert!(
            q.iter().all(|q| !q.description.contains("SME")),
            "SME should be suppressed by entity title match"
        );
        // XYZZY not in any doc title → still flagged
        let q2 = generate_ambiguous_questions_with_type(
            "# Project\n\n- Working on XYZZY initiative",
            Some("project"),
            &terms,
        );
        assert!(q2.iter().any(|q| q.description.contains("XYZZY")));
    }

    #[test]
    fn test_custom_glossary_types_from_perspective() {
        use crate::models::Document;
        // Custom glossary type "acronym" configured via perspective.yaml.
        // The doc has inline **TERM**: definitions in its content.
        let doc = Document {
            id: "c01".to_string(),
            title: "Acronyms".to_string(),
            content: "# Acronyms\n\n- **FHIR**: Fast Healthcare Interoperability Resources\n- **HL7**: Health Level Seven\n".to_string(),
            doc_type: Some("acronym".to_string()),
            ..Document::test_default()
        };
        // Without custom types, "acronym" type is not recognized as glossary,
        // so inline content terms (FHIR, HL7) are NOT extracted.
        // (The doc title "Acronyms" is always included via entity-name matching.)
        let terms_default = collect_defined_terms(&[doc.clone()]);
        assert!(
            !terms_default.contains("FHIR"),
            "inline content term FHIR should not be extracted without custom glossary_types"
        );
        assert!(
            !terms_default.contains("HL7"),
            "inline content term HL7 should not be extracted without custom glossary_types"
        );
        assert!(
            terms_default.contains("Acronyms"),
            "doc title is always included via entity-name matching"
        );
        // With custom types, inline content terms ARE extracted
        let custom = vec!["acronym".to_string()];
        let terms_custom = collect_defined_terms_with_types(&[doc], Some(&custom));
        assert!(
            terms_custom.contains("FHIR"),
            "FHIR should be extracted from content with custom glossary_types"
        );
        assert!(
            terms_custom.contains("HL7"),
            "HL7 should be extracted from content with custom glossary_types"
        );
    }
}
