//! Resolve workflow instruction constants.
#[allow(unused_imports)]
pub(crate) use crate::mcp::tools::workflow::instructions::{
    DEFAULT_RESOLVE_ANSWER_INSTRUCTION, DEFAULT_RESOLVE_ANSWER_INTRO_INSTRUCTION,
    DEFAULT_RESOLVE_APPLY_INSTRUCTION, DEFAULT_RESOLVE_CLEANUP_INSTRUCTION,
    DEFAULT_RESOLVE_QUEUE_INSTRUCTION, DEFAULT_RESOLVE_VERIFY_INSTRUCTION,
    DEFAULT_RESOLVE_WEAK_SOURCE_TRIAGE_INSTRUCTION,
};
