//! Setup workflow instruction constants.
#[allow(unused_imports)]
pub(crate) use crate::mcp::tools::workflow::instructions::{
    DEFAULT_SETUP_COMPLETE_INSTRUCTION, DEFAULT_SETUP_CREATE_INSTRUCTION,
    DEFAULT_SETUP_INIT_INSTRUCTION, DEFAULT_SETUP_PERSPECTIVE_INSTRUCTION,
    DEFAULT_SETUP_SCAN_INSTRUCTION, DEFAULT_SETUP_SOURCES_INSTRUCTION,
    DEFAULT_SETUP_VALIDATE_ERROR_INSTRUCTION, DEFAULT_SETUP_VALIDATE_OK_INSTRUCTION,
};
