//! Transition workflow instruction constants.
#[allow(unused_imports)]
pub(crate) use crate::mcp::tools::workflow::instructions::{
    DEFAULT_TRANSITION_APPLY_INSTRUCTION, DEFAULT_TRANSITION_MAINTAIN_INSTRUCTION,
    DEFAULT_TRANSITION_NOMENCLATURE_CONFIRMED, DEFAULT_TRANSITION_NOMENCLATURE_QUESTION,
    DEFAULT_TRANSITION_ORGANIZE_INSTRUCTION, DEFAULT_TRANSITION_PARSE_INSTRUCTION,
    DEFAULT_TRANSITION_REPORT_INSTRUCTION,
};
